REPLACE VIEW DP_EDW_DM_VEW.SALES_TRANS_DEVICE_ACTIVITY AS
SELECT
  EV.SALES_TRANS_ID
  ,EV.EVENT_ID
  ,EV.QUOTE_CREATED_DTTM
  ,EV.ACTIVITY_NUM
  ,EV.QUOTE_NUMBER
  ,EV.QUOTE
  ,EV.EVENT_START_TIMESTAMP
  ,EV.EVENT_END_TIMESTAMP
  ,EV.TYP
  ,EV.ACCOUNT_NAME
  ,EV.STATUS
  ,EV.EMPLOYEE
  ,EV.ACTVTY_ASSGNED_USER	--[DMART-2718, 2021-09-08] 5 new columns added
  ,EV.ACTVTY_ASSGNED_USER_DEPT
  ,EV.CREATED_BY
  ,EV.UPDATED_BY						--[DMART-3839, 5TH APR 2023, EBU-AGILITY, SPRINT-35]- new column added.
  ,EV.UPDATED_ON
  ,EV.MODIFICATION_NUM
  ,ETX.NEW_ACTIVITY
  ,ETX.PLANNED_START
  ,ETX.DESCRIPTION
  ,ETX.REPEAT_FLAG
  ,ETX.REJECT_REASON
  ,XREF.CREATED_DEVICE
  ,XREF.DEVICE_COLOR
  ,XREF.APPROVAL
  ,XREF.DEVICE_COST
  ,XREF.DEVICE_MAKE
  ,XREF.DEVICE_MEMORY
  ,XREF.DEVICE_MODEL_NAME
  ,XREF.IMEI_NUMBER
  ,XREF.ITEM_CODE
--  ,XREF.CONTRACT_TYPE
--  ,XREF.CONTRACT_STATUS
  ,EV.ACTIVITY_DURATION
  ,CASE WHEN EV.TOTAL_DURATION IS NOT NULL THEN EV.TOTAL_DURATION
  ELSE
  (EXTRACT(DAY FROM (CURRENT_TIMESTAMP(0) - QUOTE_CREATED_DTTM DAY(4) TO SECOND(0)))*(24*60.0) + EXTRACT(HOUR FROM (CURRENT_TIMESTAMP(0) - QUOTE_CREATED_DTTM DAY(4) TO SECOND(0)))*60.0 + EXTRACT(MINUTE FROM (CURRENT_TIMESTAMP(0) - QUOTE_CREATED_DTTM DAY(4) TO SECOND(0))) + EXTRACT(SECOND FROM (CURRENT_TIMESTAMP(0) - QUOTE_CREATED_DTTM DAY(4) TO SECOND(0)))/60.0)
  END AS TOTAL_DURATION
  --[DMART-3839, 5TH APR 2023, EBU-AGILITY, SPRINT-35]- new 3 columns added.
  ,EV.ORDER_NUMBER
  ,EV.ACTIVITY_COMMENTS
  ,EV.ACTIVITY_RESEND_RSN_CD
  -- DMART-3312
  ,EV.SALES_AGENT_NAME
  ,EV.SUPERVISOR_NAME
  ,EV.SERVICE_SECTION
  ,EV.ACTIVE_FLAG
  ,EV.AUTO_ASMNT_FLAG
  
  --,XREF.STCS_LEAD
  ,XREF.OPTY_PROD_REVN_ID -- [DMART-3065]

FROM
  DP_EDW_DM_TGT.SALES_TRANS_DEVICE_ACTIVITY EV
LEFT JOIN (
  SELECT 
  ETX.EVENT_ID
  ,MAX(CASE WHEN TT.TXT_TYPE_DESC='NEW ACTIVITY STATUS'   THEN ETX.EVENT_TXT_DESC END) AS NEW_ACTIVITY
  ,MAX(CASE WHEN TT.TXT_TYPE_DESC='PLANNED START'         THEN ETX.EVENT_TXT_DESC END) AS PLANNED_START
  ,MAX(CASE WHEN TT.TXT_TYPE_DESC='DESCRIPTION'           THEN ETX.EVENT_TXT_DESC END) AS DESCRIPTION
  ,MAX(CASE WHEN TT.TXT_TYPE_DESC='REPEAT FLAG'           THEN ETX.EVENT_TXT_DESC END) AS REPEAT_FLAG
  ,MAX(CASE WHEN TT.TXT_TYPE_DESC='ORDER REJECT REASON'   THEN ETX.EVENT_TXT_DESC END) AS REJECT_REASON
  FROM
  DP_EDW_VEW.EVENT_TXT ETX
  JOIN DP_EDW_VEW.TXT_TYPE TT
  ON ETX.TXT_TYPE_CD=TT.TXT_TYPE_CD
  WHERE TT.TXT_TYPE_DESC IN('NEW ACTIVITY STATUS','PLANNED START','DESCRIPTION','REPEAT FLAG','ORDER REJECT REASON')
  AND ETX.DATA_SOURCE_TYPE_CD='BSCRM'
  GROUP BY 1
) AS ETX2
  ON EV.EVENT_ID=ETX.EVENT_ID

LEFT JOIN DP_EDW_SMBB_VEW.DBB_SALES_TRANS_XREF XREF
  ON EV.SALES_TRANS_ID=XREF.SALES_TRANS_ID

--DMART-3184 ADDING GROUP BY --
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43;
